FROM python:3.11-slim

RUN apt update -y && apt install -y jq

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN ./bin/clear.sh

CMD ["python3", "src/main.py"]
