"""
The runner component
"""

import importlib
import hunter
from environment import DEBUG_MODE
from engine.engine import Engine
from exceptions import RunnerException, AlgorithmException
from .logger import logger
from .loader import Loader


class Runner:
    """
    Runner component receives the module which was prepared by the loader
    component, imports it and prepares the code trackers (Hunter). A new instance
    of engine is then created and passed to the algorithm as an argument of the
    wrapper function
    """

    def import_module(self):
        """
        Imports the module created by the loader component using importlib

        raises:
          - RunnerException: if an error occurres while importing the module
        """
        module_name = self._loader.module_name

        try:
            self._module = importlib.import_module(module_name)
            logger.debug("Importing module: success", {"module": module_name})

        except Exception as e:
            logger.debug("Importing module: error", {"module": module_name})
            raise RunnerException(e)

    def run(self):
        """
        Runs the user provided algorithm by running the module created by the
        loader component and initiates line tracing by the hunter library

        raises:
          - RunnerException: if an error occurres while importing the module
          - AlgorithmException: if an error is raised while running the algorithm
        """
        module_name = self._loader.module_name
        fun_name = self._loader.unique_id

        self.import_module()

        q1 = hunter.Q(
            module=module_name, kind="line", action=self._engine.line_callback
        )
        # In case of infinitely running code.
        # The number has no science behind it. Just picked a number that seemed reasonable
        q2 = hunter.Q(calls_gt=5000, action=hunter.Stop)
        hunter.trace(q1 | q2)

        fun = getattr(self._module, fun_name)

        logger.debug("Running <<<", {"module": module_name})

        self._engine.stopwatch.start()

        try:
            fun(self._engine, self._engine.print)
            logger.debug(">>> success")

        except RecursionError:
            raise Exception("Your code raised a recursion error. Please check it.")
        except Exception as e:
            logger.debug(">>> error")
            raise AlgorithmException(e)
        finally:
            self._engine.stopwatch.stop()

    def make_frames(self):
        """
        Engine computes the visualization frames. These frames are then returned
        """
        return self._engine.make_frames()

    def get_ticks(self):
        """
        Returns all ticks generated by the ticker until this moment. This method
        CANNOT be run unless the debug mode is on.

        returns:
          - ticks (list): all ticks generated until this moment
        """
        if not DEBUG_MODE:
            raise Exception("This feature is disabled in production mode")

        return self._engine.get_ticks()

    def get_logs(self):
        """
        Returns the logs produced by the engine. This method CANNOT be run unless
        the debug mode is on.

        returns:
          - logs (str): all logs produced by the engine so far
        """
        if not DEBUG_MODE:
            raise Exception("This feature is disabled in production mode")

        return self._engine.get_logs()

    def get_elapsed_time(self):
        """
        Returns the amount of time elapsed during the execution of the visualized
        algorithm in seconds.

        returns:
          - time (float): elapsed time in seconds
        """
        return self._engine.stopwatch.elapsed

    def __init__(self, loader: Loader | None):
        """
        Creates a new instance of Runner

        parameters:
          - loader (Loader): the loader which already loaded the config
        """
        self._loader = loader
        self._module = None
        self._engine = Engine()
